set:
  train: false
  eval: false
  debug: false
  graph: false
  gpus: 1
  num_workers: 1

path:
  home_dir: /home/mark
  root_dir: ${path.home_dir}/projects/frontendComparison
  data_dir: ${path.home_dir}/ssd/datasets/DCASE2018/
  bv_dir: ${path.home_dir}/ssd/datasets/DCASE2018/BirdVox-DCASE-20k/meta/birdvox.csv
  ff_dir: ${path.home_dir}/ssd/datasets/DCASE2018/ff1010bird/meta/ff1010.csv
  warblr_dir: ${path.home_dir}/ssd/datasets/DCASE2018/warblrb10k/meta/warblr.csv
  model: ${path.root_dir}/models
  best_model: ${path.model}/best.ckpt
  last_model: ${path.model}/latest.ckpt

features:
  frontend: pcen
  spectaugment: false
  sample_rate: 44100
  n_fft: 256
  hop_length: 128
  n_mels: 40
  f_min: 500
  f_max: 16000
  win_length: ${features.n_fft}
  window: hann
  center: true
  pad_mode: reflect

augmentation:
  time_mask: 10
  time_mask_num: 1
  freq_mask: 10
  freq_mask_num: 1

training:
  lr: 1E-2
  epochs: 100
  factor: 0.1
  patience: 5
  batch_size: 32
  class_num: 1
  pretrained: false
